sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dockerifont21/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerifont21/react-test npm test -- --coverage

after_success:
  - docker build -t dockerifont21/multi-client ./client
  - docker build -t dockerifont21/multi-nginx ./nginx
  - docker build -t dockerifont21/multi-server ./server
  - docker build -t dockerifont21/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dockerifont21/multi-client
  - docker push dockerifont21/multi-nginx
  - docker push dockerifont21/multi-server
  - docker push dockerifont21/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-1-123456789013
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY